### ISSUE TITLE
Tag versions, add pre-commit example

### ISSUE THREAD

**Issue by Bouni** [albertas/deadcode#16]
Hi, nice project, I really like it!

A few things that should be added:

### Tag versions as you release them 

`.pre-commit-config.yaml` expects a `rev` which is either 
- a tag
- a sha sum (very unintuitive to use) 
- a branch (which is mutable, not recommended)

### Add an pre-commit-config.yaml example

```yaml
  - repo: https://github.com/albertas/deadcode
    rev: 2706a6c1a4f3fd2d0c40daf066c681858cacd181
    hooks:
      - id: deadcode
```

As mentioned above, the rev should ideally be the tag of the released version. At the time of opening this issue that would be 2.4.0

### Add a `--version` or `-V` argument 

After installing its hard to figure out which version is installed.

------

Finally some questions 😄 

I run `deadcode.exe .` locally and get: Well done! ✨ 🚀 ✨

```sh
pip freeze | grep deadcode
deadcode==2.4.0
```

If I add deadcode to my `pre-commit-config.yaml` like this

```yaml
  - repo: https://github.com/albertas/deadcode
    rev: 2706a6c1a4f3fd2d0c40daf066c681858cacd181
    hooks:
      - id: deadcode
```

and run it manually with `pre-commit`, I get this:

```
deadcode.................................................................Failed
- hook id: deadcode
- exit code: 1

datamodel.py:11:0: DC03 Class `PartListDataModel` is never used
datamodel.py:50:8: DC05 Attribute `logger` is never used
datamodel.py:108:4: DC04 Method `SetValue` is never used
datamodel.py:148:4: DC04 Method `AddEntry` is never used
datamodel.py:162:4: DC04 Method `RemoveAll` is never used
datamodel.py:167:4: DC04 Method `get_all` is never used
datamodel.py:171:4: DC04 Method `get_reference` is never used
datamodel.py:175:4: DC04 Method `get_value` is never used
datamodel.py:179:4: DC04 Method `get_lcsc` is never used
datamodel.py:183:4: DC04 Method `get_footprint` is never used
datamodel.py:187:4: DC04 Method `select_alike` is never used
datamodel.py:196:4: DC04 Method `set_lcsc` is never used
datamodel.py:206:4: DC04 Method `remove_lcsc_number` is never used
datamodel.py:232:4: DC04 Method `toggle_bom_pos` is never used
```

The sha sum `2706a6c1a4f3fd2d0c40daf066c681858cacd181` is the one with the commit message "Bump version to 2.4.0".
So I guess that should be the code released, right!?
Why do they behave differently?
