### ISSUE TITLE
Is `ignore-names-if-inherits-from` ignored?

### ISSUE THREAD

**Issue by giampaolo** [albertas/deadcode#25]
Hello there.
I'm trying to use `ignore-names-if-inherits-from` within `pyproject.toml` but it seems it doesn't work as expected (ignored), e.g.:

```toml
[tool.deadcode]
ignore-names-if-inherits-from = ["ViewEventListener"]
```

Also by searching into the source code it seems it's not being used:
https://github.com/search?q=repo%3Aalbertas%2Fdeadcode%20ignore_names_if_inherits_from&type=code
Am I missing something?
